### ISSUE TITLE
npm install rive-canvas instead unpkg.com?

### ISSUE THREAD

**Issue by naychrist** [Coded-Clouds/Rive_Vue_ExampleApp#1]
Hey there, nice example! I'm working with rive and vue as well and have been struggling trying to get it to work with `locateFile: (file) => '/node_modules/rive-canvas/' + file` as per readme instead `locateFile: (file) => 'https://unpkg.com/rive-canvas@0.6.7/' + file`. I see your example has the same issue. Do you know of any fixes or leads for fixes? I would definitely prefer this for production but am keen to get this working with the module and then be able to edit it locally within that folder for testing too (to try the typescript pull request for example). Any advice appreciated, cheers.

**Comment by naychrist** [comment]
apologies that was a little premature. Seems it works if you import the module but then copy the rive.wasm file to src or public before using locateFile. Example relative path below was inside src folder:

```
import Rive from 'rive-canvas'

export default {
  data() {
    return {
      canvas: null
    }
  },
  created() {
		window.addEventListener("resize", this.onResize);
	},
	mounted() {
		Rive({
      locateFile: (file) => '../../rive-canvas/rive.wasm',
```

**Comment by danwritecode** [comment]
@naychrist thanks for figuring that out! I couldn't actually get that figure out myself. This will serve as good reference for those in the future.
